blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Join the Discord Community
    url: https://discord.gg/fbFCkYabZB
    about: "Outside of GitHub, the Odin community lives on Discord. Join our server here"